/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public int add(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        App test = new App();
        System.out.println("Summe: " + test.add(3, 3));
    }
}
