/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App 
{
    public static int countSequences(int[] input) 
    {
        if (input.length == 0) 
        {
            return 0;
        }
        
        int sequenceCount = 1;
        int previousNumber = input[0]; 
        for (int i = 1; i < input.length; i++) 
        {
            if (input[i] != previousNumber) 
            {
                sequenceCount++;
                previousNumber = input[i];
            }
        }        
        return sequenceCount;
    }

    public static String convertArrayToString(int[] input) 
    {
        StringBuilder result = new StringBuilder();
        result.append("[");
        for (int i = 0; i < input.length; i++) 
        {
            result.append(input[i]);
            if (i < input.length - 1) 
            {
                result.append(", ");
            }
        }
        result.append("]");

        return result.toString();
    }

    public static String encodeRunLength(int[] input)
    {
        if (input.length == 0)
        {
            return "[] becomes []";
        }
        
        int encodedLength = countSequences(input) * 2;
        int[] encodedArray = new int[encodedLength];
        int currentIndex = 0;

        int currentNumber = input[0];
        int count = 0;
        for (int i = 0; i < input.length; i++) 
        {
            if (input[i] == currentNumber) 
            {
                count++;
            
            }
            else 
            {
                encodedArray[currentIndex] = currentNumber;
                encodedArray[currentIndex + 1] = count;
                currentIndex += 2;
                
                currentNumber = input[i];
                count = 1;
            }
        }
        encodedArray[currentIndex] = currentNumber;
        encodedArray[currentIndex + 1] = count;

        String inputArrayString = convertArrayToString(input);
        String encodedString = convertArrayToString(encodedArray);

        return inputArrayString + " becomes " + encodedString;
    }

    public static void main(String[] args) 
    {
        int[] arr = {1, 1, 2, 3};
        String encodedResult = encodeRunLength(arr);
        
        System.out.println(encodedResult);
    }
}
