/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.lang.Math;

public class App 
{
    public static String romanString(double arabicNumber)
    {
        int arabicInt = (int)arabicNumber;
        switch (arabicInt)
        {
            case 1:
                return "I";
                
            case 5:
                return "V";
            
            case 10:
                return "X";
                
            case 50:
                return "L";
            
            case 100:
                return "C";

            case 500:
                return "D";

            case 1000:
                return "M";

        }
        return "";
    }

    public static String arabicNumberToRomanNumber(int arabicInt)
    {
        if(arabicInt > 1000 || arabicInt < 1)
        {
            return "Out of range";
        }

        StringBuilder arabicNumberAsStringBuilder = new StringBuilder();
        arabicNumberAsStringBuilder.append(arabicInt);
        String arabicNumberAsString = arabicNumberAsStringBuilder.toString();

        StringBuilder romanNumberAsString = new StringBuilder();
        
        for(int i = 0; i < arabicNumberAsString.length(); i++)
        {
            char currentDigitAsChar = arabicNumberAsString.charAt(i);
            String currentDigitAsString = Character.toString(currentDigitAsChar);
            Integer currentDigit = Integer.parseInt(currentDigitAsString);
            double place = Math.pow(10, arabicNumberAsString.length() - i - 1); //if were at 3 of 30 (so i = 0), place should be 10. 10 = 10^(length("30") - i - 1)
            double placeOfFives = place * 5;

            if(currentDigit < 4)
            {
                for(int j = 0; j < currentDigit; j++)
                {
                    romanNumberAsString.append(romanString(place));
                }
            }
            else if(currentDigit == 4)
            {
                romanNumberAsString.append(romanString(place));
                romanNumberAsString.append(romanString(placeOfFives));
            }
            else if(currentDigit == 5)
            {
                romanNumberAsString.append(romanString(placeOfFives));
            }
            else if(currentDigit < 9)
            {
                romanNumberAsString.append(romanString(placeOfFives));
                for(int j = 0; j < currentDigit - 5; j++)
                {
                    romanNumberAsString.append(romanString(place));
                }
            }
            else
            {
                romanNumberAsString.append(romanString(place));
                romanNumberAsString.append(romanString(place * 10));
            }
        }
        return romanNumberAsString.toString();
    }

    public static void main(String[] args) 
    {
        System.out.println(arabicNumberToRomanNumber(444));
    }
}
