/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppTest {
    @Test 
    public void testAdd() {
        App testApp = new App();
        assertEquals(5, testApp.add(2, 3));
    }
}
