/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest 
{
    @Test
    void testRomanNumerals() {
        // 1 to 10
        assertEquals("I", App.arabicNumberToRomanNumber(1));
        assertEquals("II", App.arabicNumberToRomanNumber(2));
        assertEquals("III", App.arabicNumberToRomanNumber(3));
        assertEquals("IV", App.arabicNumberToRomanNumber(4));
        assertEquals("V", App.arabicNumberToRomanNumber(5));
        assertEquals("VI", App.arabicNumberToRomanNumber(6));
        assertEquals("VII", App.arabicNumberToRomanNumber(7));
        assertEquals("VIII", App.arabicNumberToRomanNumber(8));
        assertEquals("IX", App.arabicNumberToRomanNumber(9));
        assertEquals("X", App.arabicNumberToRomanNumber(10));

        // Teens
        assertEquals("XIV", App.arabicNumberToRomanNumber(14));
        assertEquals("XV", App.arabicNumberToRomanNumber(15));
        assertEquals("XIX", App.arabicNumberToRomanNumber(19));

        // Tens
        assertEquals("XX", App.arabicNumberToRomanNumber(20));
        assertEquals("XXX", App.arabicNumberToRomanNumber(30));
        assertEquals("XL", App.arabicNumberToRomanNumber(40));
        assertEquals("L", App.arabicNumberToRomanNumber(50));
        assertEquals("LX", App.arabicNumberToRomanNumber(60));
        assertEquals("LXX", App.arabicNumberToRomanNumber(70));
        assertEquals("LXXX", App.arabicNumberToRomanNumber(80));
        assertEquals("XC", App.arabicNumberToRomanNumber(90));
        assertEquals("C", App.arabicNumberToRomanNumber(100));

        // Hundreds
        assertEquals("CC", App.arabicNumberToRomanNumber(200));
        assertEquals("CCC", App.arabicNumberToRomanNumber(300));
        assertEquals("CD", App.arabicNumberToRomanNumber(400));
        assertEquals("D", App.arabicNumberToRomanNumber(500));
        assertEquals("DC", App.arabicNumberToRomanNumber(600));
        assertEquals("DCC", App.arabicNumberToRomanNumber(700));
        assertEquals("DCCC", App.arabicNumberToRomanNumber(800));
        assertEquals("CM", App.arabicNumberToRomanNumber(900));
        assertEquals("M", App.arabicNumberToRomanNumber(1000));

        // Edge cases around 100, 500, and 1000
        assertEquals("CI", App.arabicNumberToRomanNumber(101));
        assertEquals("CDXLIV", App.arabicNumberToRomanNumber(444));
        assertEquals("CMXCIX", App.arabicNumberToRomanNumber(999));
    }


}
